name: jetkiz_restaurant
description: "JETKIZ restaurant application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  http_parser: ^4.0.2
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1
  dio: ^5.4.0
  intl: ^0.20.2
  flutter_image_compress: ^2.3.0
  video_player: ^2.9.2
  just_audio: ^0.9.46

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true